extern const GeoLayout mushroom_top_geo[];
extern Lights1 mushroom_top_f3dlite_material_019_lights;
extern Lights1 mushroom_top_f3dlite_material_018_lights;
extern u8 mushroom_top_Shape_45_ci8[];
extern u8 mushroom_top_Shape_45_pal_rgba16[];
extern u8 mushroom_top_Shape_46_ci8[];
extern u8 mushroom_top_Shape_46_pal_rgba16[];
extern Vtx mushroom_top_000_displaylist_mesh_layer_1_vtx_0[19];
extern Gfx mushroom_top_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx mushroom_top_000_displaylist_mesh_layer_1_vtx_1[32];
extern Gfx mushroom_top_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_mushroom_top_f3dlite_material_019[];
extern Gfx mat_revert_mushroom_top_f3dlite_material_019[];
extern Gfx mat_mushroom_top_f3dlite_material_018[];
extern Gfx mat_revert_mushroom_top_f3dlite_material_018[];
extern Gfx mushroom_top_000_displaylist_mesh_layer_1[];
