#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "mushroom_top/geo.inc.c"
#include "trunk/geo.inc.c"
#include "toad/geo.inc.c"
#include "luiginpc/geo.inc.c"
#include "flying_boost/geo.inc.c"
#include "banana/geo.inc.c"
#include "ukiki/geo.inc.c"
#include "rock/geo.inc.c"
#include "seesaw/geo.inc.c"
#include "seesaw2/geo.inc.c"
#include "elevator/geo.inc.c"