extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_f3dlite_material_033_lights;
extern Lights1 jrb_dl_f3dlite_material_034_lights;
extern Lights1 jrb_dl_f3dlite_material_035_lights;
extern Lights1 jrb_dl_f3dlite_material_041_lights;
extern Lights1 jrb_dl_f3dlite_material_lights;
extern u8 jrb_dl_DONKEY_KONG_64_2ACE0158_0_2_all_ci8[];
extern u8 jrb_dl_DONKEY_KONG_64_2ACE0158_0_2_all_pal_rgba16[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_0[1316];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_1[4];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_2[4];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_2[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_3[4];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_3[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_4[1120];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_4[];
extern Gfx mat_jrb_dl_f3dlite_material_033[];
extern Gfx mat_jrb_dl_f3dlite_material_034[];
extern Gfx mat_jrb_dl_f3dlite_material_035[];
extern Gfx mat_jrb_dl_f3dlite_material_041[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx mat_revert_jrb_dl_f3dlite_material[];
extern Gfx jrb_dl_Plane_001_mesh_layer_1[];
